const DistrictEnums = [
"Agincourt South-Malvern West",
"Agincourt North",
"Alderwood",
"Annex",
"Banbury-Don Mills",
"Bathurst Manor",
"Bayview Village",
"Bayview Woods-Steeles",
"Bedford Park-Nortown",
"Beechborough-Greenbrook",
"Bendale",
"Birchcliffe-Cliffside",
"Black Creek",
"Bloor West Village",
"Bridle Path-Sunnybrook-York Mills",
"Briar Hill-Belgravia",
"Broadview North",
"Brookhaven-Amesbury",
"Cabbagetown-South St. James Town",
"Caledonia-Fairbank",
"Casa Loma",
"Centennial Scarborough",
"Church-Yonge Corridor",
"Clairlea-Birchmount",
"Clanton Park",
"Cliffcrest",
"Corso Italia-Davenport",
"Crossroads",
"Danforth",
"Danforth Village-East York",
"Don Valley Village",
"Downsview-Roding-CFB",
"Dufferin Grove",
"East York",
"East End-Danforth",
"Edgeley",
"Eglinton East",
"Elms-Old Rexdale",
"Englemount-Lawrence",
"Eringate-Centennial-West Deane",
"Etobicoke West Mall",
"Flemingdon Park",
"Forest Hill North",
"Forest Hill South",
"Glenfield-Jane Heights",
"Greenwood-Coxwell",
"Guildwood",
"Henry Farm",
"High Park North",
"High Park-Swansea",
"Highland Creek",
"Humewood-Cedarvale",
"Ionview",
"Islington-City Centre West",
"Junction Area",
"Keelesdale-Eglinton West",
"Kingsview Village-The Westway",
"Kingsway South",
"L'Amoreaux",
"Lambton Baby Point",
"Lansing-Westgate",
"Lawrence Park North",
"Lawrence Park South",
"Leaside-Bennington",
"Little Italy",
"Long Branch",
"Maple Leaf",
"Markland Wood",
"Milliken",
"Mimico",
"Mount Dennis",
"Mount Olive-Silverstone-Jamestown",
"Mount Pleasant East",
"Mount Pleasant West",
"New Toronto",
"Newtonbrook East",
"Newtonbrook West",
"Niagara",
"North Riverdale",
"O'Connor-Parkview",
"Oakridge",
"Oakwood Village",
"Palmerston-Little Italy",
"Parkwoods-Donalda",
"Pelmo Park-Humberlea",
"Playter Estates-Danforth",
"Pleasant View",
"Princess-Rosethorn",
"Regent Park",
"Rockcliffe-Smythe",
"Roncesvalles",
"Rosedale-Moore Park",
"Rouge",
"Runnymede-Bloor West Village",
"Rustic",
"Scarborough Village",
"South Parkdale",
"St. Andrew-Windfields",
"St. James Town",
"Steeles",
"Stonegate-Queensway",
"Tam O'Shanter-Sullivan",
"The Beaches",
"The Peanut",
"Thistletown-Beaumond Heights",
"Thorncliffe Park",
"Trinity-Bellwoods",
"University",
"Victoria Village",
"Waterfront Communities-The Island",
"West Humber-Clairville",
"Westminster-Branson",
"Weston",
"Weston-Pellam Park",
"Wexford/Maryvale",
"Willowdale East",
"Willowdale West",
"Willowridge-Martingrove-Richview",
"Woburn",
"Woodbine Corridor",
"Woodbine-Lumsden",
"Wychwood",
"Yonge-Eglinton",
"Yonge-St. Clair",
"York University Heights",
"Yorkdale-Glen Park"
];

export default DistrictEnums;
